### ISSUE TITLE
[ISSUE] macOS makefile needs work

### ISSUE THREAD

**Issue by karetsu** [karetsu/woffle#33]
**Describe the bug**
On a clean macOS installation with no homebrew installed the make is 3.8 and `xcode-select --install`  doesn't link libstdc++ which fasttext relies on to build the wheel. Figure out this mess.

**To Reproduce**
1. Clean macOS installation
2. run `make`
3. `tail -f setup.log`

**Expected behavior**
`make` should complete without errors, this will need a check to see OS type and install what it needs to in order to work

**Desktop (please complete the following information):**
 - OS:  macOS
 - Python version: NA
 - Makefile installation: No

**Comment by David-Pugh** [comment]
I used the following as inspiration:
https://github.com/facebookresearch/fastText/issues/669
using the command export MACOSX_DEPLOYMENT_TARGET=10.9 allowed me to install fastext

**Comment by karetsu** [comment]
*should* be fixed in 4a47d76 - will test it next week
